name: Pull Request

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  7.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test